# Generated by Django 4.2.4 on 2023-08-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
