# Generated by Django 4.2.4 on 2023-08-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
