# Generated by Django 4.2.4 on 2023-08-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_location_end_date_alter_location_start_date'),
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.location'),
        ),
    ]
